### ISSUE TITLE
Add last updated to list

### ISSUE THREAD

**Issue by roughiain** [jsuarezruiz/awesome-dotnet-maui#22]
**Issue:**
A big problem with the previous Xamarin list was you never knew if a library was up to date with the latest releases, it could have been last updated 5 years ago and for a much older version of Xamarin.

**Possible Solution:**
 A script could be created to parse the list of URLs and get the last updated date from the GitHub repo. Then scheduled as an automated job/pipeline.

**Comment by jsuarezruiz** [comment]
Nice idea. Will try to include it.

**Comment by jsuarezruiz** [comment]
![image](https://user-images.githubusercontent.com/6755973/190850800-a58537fc-7623-4511-858d-94b6bfec5501.png)
