### ISSUE TITLE
Add Plugin.FirebasePushNotifications

### ISSUE THREAD

**Issue by thomasgalliker** [jsuarezruiz/awesome-dotnet-maui#73]
Source code:
[https://github.com/thomasgalliker/Plugin.FirebasePushNotifications ](https://github.com/thomasgalliker/Plugin.FirebasePushNotifications )

Nuget:
https://www.nuget.org/packages/Plugin.FirebasePushNotifications

**Comment by EGoverde** [comment]
I have included your suggestion in the PR I've created [here](https://github.com/jsuarezruiz/awesome-dotnet-maui/pull/76).

**Comment by thomasgalliker** [comment]
Thank you, @EGoverde
