### ISSUE TITLE
Add Blazor UI

### ISSUE THREAD

**Issue by doddgu** [jsuarezruiz/awesome-dotnet-maui#8]
MASA Blazor: https://github.com/BlazorComponent/MASA.Blazor

It's a material design Blazor UI Component Library.
We try to support BlazorWebView in MAUI. And it's available through incomplete testing. I think BlazorWebView is also a good choice for MAUI, but it should be made clear that this is not the same as XAML

**Comment by jsuarezruiz** [comment]
Added. Thanks!
